---
- name: Initialize Digital Ocean volumes if configured
  when: digital_ocean_volumes is defined
  block:
    # Check if mount point exists (runs once per volume)
    - name: Check if mount point exists
      ansible.builtin.stat:
        path: "{{ item.mount_point }}"
      register: mount_point
      loop: "{{ digital_ocean_volumes }}"
      loop_control:
        index_var: idx

    - name: Create mount point if does not exist
      ansible.builtin.file:
        path: "{{ item.mount_point }}"
        state: directory
        recurse: yes
      loop: "{{ digital_ocean_volumes }}"
      loop_control:
        index_var: idx
      when: digital_ocean_volumes is defined and (mount_point.results[idx].stat.exists is defined and mount_point.results[idx].stat.exists == False)

    - name: Check if volume is already mounted
      ansible.builtin.shell: mount | grep -F "{{ item.mount_point }}"
      register: mount_check
      failed_when: false
      changed_when: false
      loop: "{{ digital_ocean_volumes }}"
      loop_control:
        index_var: idx

    # TO DO - CHECK IF FILE SYSTEM NEEDS FORMATING - DANGER, SO LETS KEEP THIS COMMENTED FOR NOW
    # - name: Format volume
    #   mkfs:
    #     fstype: ext4
    #     state: formated
    #     dev: "/dev/disk/by-id/{{volume_id}}"
    #   with_items: "{{ digital_ocean_volumes }}"

    - name: Mount filesystem
      mount:
        fstype: ext4
        src: "/dev/disk/by-id/{{ item.volume_id }}"
        path: "{{ item.mount_point }}"
        state: mounted
        opts: discard,defaults,nofail
        boot: true
      register: mount_info
      loop: "{{ digital_ocean_volumes }}"
      loop_control:
        index_var: idx
      when: digital_ocean_volumes is defined and (mount_check is not defined or (mount_check.results is defined and mount_check.results|length > idx and mount_check.results[idx].rc != 0))